import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './components/Providers';
import SignButton from './components/SignButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'blog-diary',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <div className='flex justify-between'>
            <span className='logo font-bold'>MONBlog</span>
            <SignButton />
          </div>
          <div className='outside'>{children}</div>
        </Providers>
      </body>
    </html>
  );
}
